source :rubygems

gem 'thin', '~> 1.3.1'
gem 'sinatra', '~> 1.3.2'
gem 'sinatra-contrib', '~> 1.3.1'
gem 'sinatra-flash', '~> 0.3.0', :require => 'sinatra/flash'
gem 'pusher', '~> 0.9.2'
gem 'redis', '~> 2.2.2'
